[phases.setup]
aptPkgs = ['python3', 'python3-pip']

[phases.install]
cmds = [
    'ln -s /usr/bin/python3 /usr/bin/python',
    'npm ci'
]

[phases.build]
cmds = ['npm run build']

[start]
# Forgot to run the server
cmd = "npm start & node ./server/app.js"